### ISSUE TITLE
Regel 305 auch für Publikationsmodell gültig?

### ISSUE THREAD

**Issue by barpastu** [edigonzales/modellbasierte-datenerfassung-handbuch#10]
Gilt die Regel 305 auch für das Publikationsmodell? z.B. wenn mehrere Dokumente in einem Attribut aufgeführt werden, so heisst das Attribut Dokument oder Dokumente?

**Comment by edigonzales** [comment]
Tendiere zu Plural. Es findet sich beides in den gefundenen Beispielen (BAG OF..., was ja plusminus dem entspricht).

Fixed [https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a](https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a)
