### ISSUE TITLE
Regel 603 - Verwendung

### ISSUE THREAD

**Issue by barpastu** [edigonzales/modellbasierte-datenerfassung-handbuch#11]
Wann muss eine OID verwendet werden?

**Comment by edigonzales** [comment]
Immer. Bezüglich der gewünschten Aussage ist es nicht genügend präzis beschrieben. Nächster Versuch. Siehe auch Referenzhandbuch Kapitel 1.4.5.

fixed [https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a](https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a)
