### ISSUE TITLE
Modellierungsprozess - Link zur Checkliste aktualisieren

### ISSUE THREAD

**Issue by barpastu** [edigonzales/modellbasierte-datenerfassung-handbuch#15]
Neu H:\BJSVW\Agi\KGDM\Vorlagen\Checkliste_DM_V7.docx statt H:\BJSVW\Agi\KGDM\Vorlagen\Checkliste_DM_V6.docx

**Comment by edigonzales** [comment]
Habs bissle nachhaltiger geschrieben.

**Comment by edigonzales** [comment]
[https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/a5f792ab4ed116af037c9b0d04c2df01122dd86c](https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/a5f792ab4ed116af037c9b0d04c2df01122dd86c)
