### ISSUE TITLE
Formatierung der Liste der Standardoptionen

### ISSUE THREAD

**Issue by schmandr** [edigonzales/modellbasierte-datenerfassung-handbuch#17]
Könntest du bitte im Kap. _3.4. Testen_ die Liste der Standardoptionen so umformatieren, dass man sie direkt in den ili2pg-Befehl kopieren kann? - Vielen Dank.

**Comment by edigonzales** [comment]
see [https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/ff8a6c0569480ca1197423d253ef32ef356ed639](https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/ff8a6c0569480ca1197423d253ef32ef356ed639)
