### ISSUE TITLE
Kap. 3.4: SET ROLE sogis_admin; ist nicht mehr aktuell

### ISSUE THREAD

**Issue by schmandr** [edigonzales/modellbasierte-datenerfassung-handbuch#18]
SET ROLE sogis_admin;
muss neu 
SET ROLE admin;
lauten.

**Comment by edigonzales** [comment]
fixed: https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/661c3b8496b4e719be2a88c38d994808042bf894
