### ISSUE TITLE
Konflikt Regel 103 und Beispielheader

### ISSUE THREAD

**Issue by barpastu** [edigonzales/modellbasierte-datenerfassung-handbuch#7]
Entweder muss die Regel 103 gelöscht werden oder der Beispielheader entsprechend der Regel 103 ergänzt werden.

**Comment by edigonzales** [comment]
Regel 103 gelöscht.

Fixed [https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a](https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a)
