### ISSUE TITLE
Konflikt Regel 207 und Beispielheader

### ISSUE THREAD

**Issue by barpastu** [edigonzales/modellbasierte-datenerfassung-handbuch#8]
Entweder muss die Regel 207 gelöscht werden oder der Beispielheader angepasst werden.

**Comment by edigonzales** [comment]
Regel 207 gelöscht.

Fixed [https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a](https://github.com/sogis/modellbasierte-datenerfassung-handbuch/commit/b78d157b88b3c3b5f16348abe41725ab7c01297a)
