### ISSUE TITLE
ili2pg-Version definieren

### ISSUE THREAD

**Issue by barpastu** [edigonzales/modellbasierte-datenerfassung-handbuch#9]
ili2pg-Version muss festgelegt werden (werkzeuge.adoc)

**Comment by edigonzales** [comment]
Und dazu die Frage: Wie gehen wir mit Änderungen um? Irgendeinmal will/muss man die Version ändern.

**Comment by barpastu** [comment]
Können wir uns nicht auf eine spezifische Version einigen, welche momentan all unseren Ansprüchen genügt, und diese dann solange verwenden, bis es einen guten Grund gibt die Version zu wechseln? Dies müsste dann natürlich jeweils kommuniziert werden.

**Comment by edigonzales** [comment]
Bemerkung: Eventuell lässt sich die Version (*notfalls* und *ausnahmsweise*) im build.gradle forcen. -> ausprobieren.

**Comment by edigonzales** [comment]
`configurations.all {`
 ` resolutionStrategy {`
    `force 'ch.interlis:ili2pg:3.11.3'`
 ` }`
`}`
